### ISSUE TITLE
EISDIR error when running migrate from Azure DevOps release pipeline

### ISSUE THREAD

**Issue by mdecap** [nkdAgility/Azure-DevOps-Process-Tools#13]
I am trying to get this setup to run in a pipeline and receive the following error:

2023-06-16T16:53:22.4138884Z [VERBOSE] [2023-06-16T16:53:22.383Z] Begin step 'Write process payload to file'.
2023-06-16T16:53:22.4139264Z [VERBOSE] [2023-06-16T16:53:22.393Z] Exception message:EISDIR: illegal operation on a directory, open 'D:\a\r1\a'
2023-06-16T16:53:22.4139635Z Call stack:Error: EISDIR: illegal operation on a directory, open 'D:\a\r1\a'
2023-06-16T16:53:22.4142917Z     at Object.openSync (node:fs:601:3)
2023-06-16T16:53:22.4143481Z     at Object.writeFileSync (node:fs:2249:35)
2023-06-16T16:53:22.4144837Z     at NodeJsUtility.writeJsonToFile (C:\npm\prefix\node_modules\process-migrator\build\nodejs\nodejs\NodeJsUtilities.js:19:20)
2023-06-16T16:53:22.4145349Z     at C:\npm\prefix\node_modules\process-migrator\build\nodejs\nodejs\main.js:40:78
2023-06-16T16:53:22.4146049Z     at Engine.Task (C:\npm\prefix\node_modules\process-migrator\build\nodejs\common\Engine.js:12:27)
2023-06-16T16:53:22.4146547Z     at main (C:\npm\prefix\node_modules\process-migrator\build\nodejs\nodejs\main.js:40:35)
2023-06-16T16:53:22.4147033Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-06-16T16:53:22.4147483Z [ERROR] [2023-06-16T16:53:22.393Z] Encountered unkonwn error, check log file for details.
2023-06-16T16:53:22.4412007Z ##[error]Process-Migrator FAILED: Call stack:Error: EISDIR: illegal operation on a directory, open 'D:\a\r1\a' [ERROR] [2023-06-16T16:53:22.393Z] Encountered unkonwn error, check log file for details.
2023-06-16T16:53:22.4423540Z 
2023-06-16T16:53:22.4423791Z 
2023-06-16T16:53:22.4666536Z ##[section]Finishing: Azure DevOps Services Process migrate

**Comment by walkerjono** [comment]
I also get a similar error to this when running the following Azure DevOps pipeline config:

```
trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: ineritedprocessmigration@1
  inputs:
    command: 'migrate'
    sourceAccount: 'source'
    sourceProcessName: 'Test'
    targetAccount: 'target'
    targetProcessName: 'Test'
    logFilename: 'output/processMigrator.log'
```
> note: actual source and target account names have been replaced.

The error received is:
```
2024-02-06T02:43:04.0332105Z ##[section]Starting: ineritedprocessmigration
2024-02-06T02:43:04.0559238Z ==============================================================================
2024-02-06T02:43:04.0559430Z Task         : Azure DevOps Services Process (Inherited)
2024-02-06T02:43:04.0560521Z Description  : Supports migration/import/export of inherited processes from Azure DevOps Service Organisations
2024-02-06T02:43:04.0560696Z Version      : 1.0.1
2024-02-06T02:43:04.0560761Z Author       : naked Agility Limited - Martin Hinshelwood
2024-02-06T02:43:04.0560854Z Help         : v1.0.0.1 [More Information](https://github.com/nkdAgility/vsts-process-template-task#readme)
2024-02-06T02:43:04.0561001Z ==============================================================================
2024-02-06T02:43:05.6154060Z 
2024-02-06T02:43:39.2620125Z npm WARN deprecated vss-web-extension-sdk@5.141.0: Package no longer supported. Please use https://www.npmjs.com/package/azure-devops-extension-sdk instead.
2024-02-06T02:43:40.5429650Z 
2024-02-06T02:43:40.5430574Z added 35 packages in 13s
2024-02-06T02:43:40.5430879Z 
2024-02-06T02:43:40.5431100Z 11 packages are looking for funding
2024-02-06T02:43:40.5431359Z   run `npm fund` for details
2024-02-06T02:43:42.4219609Z Path                                                                           
2024-02-06T02:43:42.4220567Z ----                                                                           
2024-02-06T02:43:42.4221654Z D:\a\_tasks\ineritedprocessmigration_c6e8cd46-7141-41d1-b21e-9932e08fa67f\1.0.1
2024-02-06T02:43:42.4221850Z 
2024-02-06T02:43:42.4223192Z LastWriteTime : 2/6/2024 2:43:05 AM
2024-02-06T02:43:42.4223764Z Length        : 609
2024-02-06T02:43:42.4224376Z Name          : configuration.json
2024-02-06T02:43:42.4225185Z 
2024-02-06T02:43:42.4226106Z 
2024-02-06T02:43:42.4229146Z sourceAccountUrl   : https://dev.azure.com/source
2024-02-06T02:43:42.4230728Z sourceAccountToken : ***
2024-02-06T02:43:42.4231477Z sourceProcessName  : Test
2024-02-06T02:43:42.4231993Z targetAccountUrl   : https://target.visualstudio.com/
2024-02-06T02:43:42.4232801Z targetAccountToken : ***
2024-02-06T02:43:42.4233492Z targetProcessName  : Test
2024-02-06T02:43:42.4236027Z options            : @{processFilename=D:\a\1\s; logLevel=verbose; logFilename=D:\a\1\s\output\processMigrator.log}
2024-02-06T02:43:42.4237893Z 
2024-02-06T02:43:42.4248229Z [INFORMATION] [2024-02-06T02:43:40.881Z] Full log is sent to 'D:\a\1\s\output\processMigrator.log' 
2024-02-06T02:43:42.4248960Z [INFORMATION] [2024-02-06T02:43:40.884Z] We are running inside a TTY does not support RAW mode, you must cancel operation with CTRL+C
2024-02-06T02:43:42.4249973Z [VERBOSE] [2024-02-06T02:43:40.885Z] Begin step 'Get rest client on source account 'https://dev.azure.com/walkerscott-staging''.
2024-02-06T02:43:42.4252436Z [VERBOSE] [2024-02-06T02:43:41.281Z] Finished step 'Get rest client on source account 'https://dev.azure.com/walkerscott-staging''.
2024-02-06T02:43:42.4253053Z [INFORMATION] [2024-02-06T02:43:41.282Z] Export process started.
2024-02-06T02:43:42.4254421Z [VERBOSE] [2024-02-06T02:43:41.282Z] Begin step 'Get source process Id from name'.
2024-02-06T02:43:42.4263963Z [VERBOSE] [2024-02-06T02:43:41.357Z] Finished step 'Get source process Id from name'.
2024-02-06T02:43:42.4266464Z [VERBOSE] [2024-02-06T02:43:41.357Z] Begin step 'Get artifacts from source process'.
2024-02-06T02:43:42.4267114Z [VERBOSE] [2024-02-06T02:43:42.379Z] Finished step 'Get artifacts from source process'.
2024-02-06T02:43:42.4268019Z [INFORMATION] [2024-02-06T02:43:42.380Z] Export process completed.
2024-02-06T02:43:42.4268595Z [VERBOSE] [2024-02-06T02:43:42.381Z] Begin step 'Write process payload to file'.
2024-02-06T02:43:42.4269199Z [VERBOSE] [2024-02-06T02:43:42.390Z] Exception message:EISDIR: illegal operation on a directory, open 'D:\a\1\s'
2024-02-06T02:43:42.4269734Z Call stack:Error: EISDIR: illegal operation on a directory, open 'D:\a\1\s'
2024-02-06T02:43:42.4270091Z     at Object.openSync (node:fs:603:3)
2024-02-06T02:43:42.4272665Z     at Object.writeFileSync (node:fs:2324:35)
2024-02-06T02:43:42.4273389Z     at NodeJsUtility.writeJsonToFile (C:\npm\prefix\node_modules\process-migrator\build\nodejs\nodejs\NodeJsUtilities.js:19:20)
2024-02-06T02:43:42.4274247Z     at C:\npm\prefix\node_modules\process-migrator\build\nodejs\nodejs\Main.js:40:78
2024-02-06T02:43:42.4275663Z     at Engine.Task (C:\npm\prefix\node_modules\process-migrator\build\nodejs\common\Engine.js:12:27)
2024-02-06T02:43:42.4276251Z     at main (C:\npm\prefix\node_modules\process-migrator\build\nodejs\nodejs\Main.js:40:35)
2024-02-06T02:43:42.4276700Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-02-06T02:43:42.4279402Z [ERROR] [2024-02-06T02:43:42.390Z] Encountered unkonwn error, check log file for details.
2024-02-06T02:43:42.4718345Z ##[error]Process-Migrator FAILED: Call stack:Error: EISDIR: illegal operation on a directory, open 'D:\a\1\s' [ERROR] [2024-02-06T02:43:42.390Z] Encountered unkonwn error, check log file for details.
2024-02-06T02:43:42.4734854Z 
2024-02-06T02:43:42.4735551Z 
2024-02-06T02:43:42.5046238Z ##[section]Finishing: ineritedprocessmigration
```

would love to use this if possible and happy to assist with getting it resolved
